/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.carreras.common.emulador;

import com.carreras.common.util.StringUtil;
import com.carreras.common.util.TiemposHelper;


/**
 *
 * @author fanky
 */
public class FrmEmulador extends javax.swing.JFrame {

    /** Creates new form FrmEmular */
    public FrmEmulador() {
        initComponents();
    }
    private Double[] getTiemposIngresados(){
        Double[] tiempos = new Double[3];
        tiempos[0] = Double.parseDouble(txtReaccion.getText());
        tiempos[1] = Double.parseDouble(txtCienMetros.getText());
        tiempos[2] = Double.parseDouble(txtFin.getText());
        
        return tiempos;
    }
    private void enviaTiempos(Integer nroCarril){
        MensajeCarril mensajeCarril = new MensajeCarril(nroCarril, getTiemposIngresados());
        boolean sent = ArduinoTCPClient.sendCommand(mensajeCarril);
        lblEstado.setText(sent?"Mensaje Enviado":"Mensaje No Enviado");
    }
    private void autoGeneraTiempos(){
        //si el final esta ingresado --> generar los dos primeros.
        String tiempoFin = txtFin.getText();
        Double[] tiempos = TiemposHelper.getTiemposAleatorios();
        if(!StringUtil.isEmpty(tiempoFin)){
            tiempos = TiemposHelper.getTiemposTiempoFin(Double.parseDouble(tiempoFin));
        }
        txtReaccion.setText(tiempos[0].toString());
        txtCienMetros.setText(tiempos[1].toString());
        txtFin.setText(tiempos[2].toString());
        
        
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtReaccion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCienMetros = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFin = new javax.swing.JTextField();
        btnAutoGen = new javax.swing.JButton();
        btnCarril1 = new javax.swing.JButton();
        btnCarril2 = new javax.swing.JButton();
        lblEstado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new java.awt.GridLayout(0, 2));

        jLabel1.setText("Tiempo Reaccion");
        jPanel1.add(jLabel1);
        jPanel1.add(txtReaccion);

        jLabel2.setText("Tiempo 100Mts");
        jPanel1.add(jLabel2);
        jPanel1.add(txtCienMetros);

        jLabel3.setText("Tiempo Fin");
        jPanel1.add(jLabel3);
        jPanel1.add(txtFin);

        btnAutoGen.setText("AutoGen");
        btnAutoGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutoGenActionPerformed(evt);
            }
        });

        btnCarril1.setText("Enviar a Carril 1");
        btnCarril1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarril1ActionPerformed(evt);
            }
        });

        btnCarril2.setText("Enviar a Carril 2");
        btnCarril2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarril2ActionPerformed(evt);
            }
        });

        lblEstado.setText("Estado:");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, btnCarril2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                    .add(btnAutoGen, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                    .add(btnCarril1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE))
                .addContainerGap())
            .add(lblEstado, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(btnAutoGen)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(btnCarril1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(btnCarril2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(lblEstado))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCarril1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarril1ActionPerformed
        enviaTiempos(1);
    }//GEN-LAST:event_btnCarril1ActionPerformed

    private void btnCarril2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarril2ActionPerformed
        enviaTiempos(2);
    }//GEN-LAST:event_btnCarril2ActionPerformed

    private void btnAutoGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutoGenActionPerformed
        autoGeneraTiempos();
    }//GEN-LAST:event_btnAutoGenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEmulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEmulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEmulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEmulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FrmEmulador().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutoGen;
    private javax.swing.JButton btnCarril1;
    private javax.swing.JButton btnCarril2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JTextField txtCienMetros;
    private javax.swing.JTextField txtFin;
    private javax.swing.JTextField txtReaccion;
    // End of variables declaration//GEN-END:variables
}
